name: Docker Builder
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GHCR_USER: ziyad-mabrouk
  TAG: v1.0

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # Telegraf
          - NAME: telegraf
            DOCKERFILE: ./docker/telegraf/Dockerfile
            CONTEXT: ./docker/telegraf

          # srsRAN project (release_avx512)
          # - NAME: srsran-gnb
          #   DOCKERFILE: ./docker/Dockerfile
          #   CONTEXT: ./
          #   MARCH: x86-64-v4
          #   PLATFORM: amd64
          #   UHD_VERSION: "4.7.0.0"
          #   DPDK_VERSION: "24.11.2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ env.GHCR_USER }}" --password-stdin

      - name: Build ${{ matrix.NAME }}
        run: |
          docker build \
            --tag ${{ matrix.NAME }}:${{ env.TAG }} \
            -f ${{ matrix.DOCKERFILE }} \
            ${{ matrix.CONTEXT }} \
            --build-arg MARCH="${{ matrix.MARCH }}" \
            --build-arg UHD_VERSION="${{ matrix.UHD_VERSION }}" \
            --build-arg DPDK_VERSION="${{ matrix.DPDK_VERSION }}"

      - name: Tag & Push to GHCR
        run: |
          IMAGE_URI=ghcr.io/${{ env.GHCR_USER }}/${{ matrix.NAME }}:${{ env.TAG }}
          docker tag ${{ matrix.NAME }}:${{ env.TAG }} "$IMAGE_URI"
          docker push "$IMAGE_URI"

      - name: Log out of GHCR
        if: always()
        run: docker logout ghcr.io
